name: "Deploy and Release Android app"

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')

    env:
      JAVA_VERSION: '17'
      NODE_VERSION: '20'
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get the tag name
        id: get_tag_name
        run: |
          echo "Version Name: $GITHUB_REF" >> $GITHUB_STEP_SUMMARY
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Get the version code
        id: get_version_code
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "Version Code: $GITHUB_RUN_NUMBER" >> $GITHUB_STEP_SUMMARY
          echo "VERSION_CODE=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Update the versionName and versionCode
        run: |
          sed -i "s/versionName \".*\"/versionName \"$TAG_NAME\"/g" android/app/build.gradle
          sed -i "s/versionCode .*/versionCode $VERSION_CODE/g" android/app/build.gradle

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: adopt
          cache: gradle
          token: ${{github.token}}

      - name: Setup Gradle Cache
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Run npm Install
        run: |
             npm i

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Build application
        run: |
          cd android
          ./gradlew assembleRelease
          ./gradlew bundleRelease
          mv app/build/outputs/bundle/release/*.aab app/build/outputs/apk/release
          cd ..

      - name: Sign app APK
        uses: filippoLeporati93/android-release-signer@v1
        id: sign_app
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            ${{ env.SIGNED_RELEASE_FILE_0 }}
            ${{ env.SIGNED_RELEASE_FILE_1 }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.SIGNED_RELEASE_FILE_0 }}
            ${{ env.SIGNED_RELEASE_FILE_1 }}
          prerelease: ${{ contains(github.ref, 'pre') }}
          make_latest: legacy
          generate_release_notes: true
