name: "Deploy and Release Android app"

on:
  workflow_dispatch:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: deploy

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: gradle
          token: ${{github.token}}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Run npm Install
        run: |
             npm i

      - name: Build application
        run: |
             cd android
             ./gradlew assembleRelease
             ./gradlew bundleRelease

      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: |
            android/app/build/outputs/apk/release
            android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            ${{steps.sign_app.signedReleaseFile0}}
            ${{steps.sign_app.signedReleaseFile1}}

      - name: Get Previous tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          fallback: 0.0.0

      - name: Get next version
        id: next
        uses: 'WyriHaximus/github-action-next-release-version@1.0.0'
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: App Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ github.token }}"
          automatic_release_tag: "${{ steps.next.outputs.version }}"
          prerelease: true
          title: "IMS-App release ${{steps.next.outputs.version}}"
          files: |
            ${{ steps.sign_app.signedReleaseFile0 }}
            ${{ steps.sign_app.signedReleaseFile1 }}
